name: Build branch_name
on:
  push:
    branches:
      - 'branch_name'
  schedule:
    - cron: '0 schedule_num * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/archlinux365/9318-archlinux-docker/root:latest
      volumes:
        - /home/runner/work/alterdir/alterdir:/tmp/alterdir
      options: "--privileged"
    steps:
      - name: 1. Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.MY_SF_SSH }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - uses: actions/checkout@v2
        with:
          ref: branch_name
      - name: 2. build
        run: ./6.ci.sh
      - name: 3. Get build_no
        id: build_no
        run: echo "::set-output name=build_no::$GITHUB_REF_NAME-$GITHUB_RUN_NUMBER"
      - name: 4. get sf url
        id: uploadiso
        run: echo "::set-output name=url::Please Download pkg From SourceForge https://sourceforge.net/projects/archlinux365/files/9329-archlinux-aur-build/x86_64/"
      - name: 5. Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.build_no.outputs.build_no }}
          name: ${{ steps.build_no.outputs.build_no }}
          body: ${{steps.uploadiso.outputs.url}}
          draft: false
          prerelease: false
